### PR TITLE
Simplified tileClients and newLayout functions

### PR DESCRIPTION
**Pull request by 3ximus**
Hey, its me again!
I'm having some free time so i decided to go over some of your code and make it cleaner with less repetition. The functionality is still the same but I think its more readable this way and I haded some comments to help.
I'm mostly doing this to see how javascript works since I never programmed with it, so this is a nice practice.
Hope you don't mind me doing this. If you would like me to do something specific I don't mind helping out.
Cheers mate!

### CODE REVIEW

**Comment by 3ximus** [comment]
Ups, I noticed this introduces a bug when resizing a window, if a tile fills all the screen height, resizing it doesn't cap the heigh...
Sorry about this, I'll fix it later today

**Comment by Jazqa** [comment]
This script is some of the first "serious" code I've ever written and contains a ton of ugly switch cases. I'll merge this tomorrow. Thank you for contributing once again! I'm quite busy myself so I truly appreciate all the help!

**Comment by 3ximus** [comment]
No problem! I've fixed the issues and its working fine now -> ffe2616

**Comment by Jazqa** [comment]
Flawless work. Way cleaner than my old code. Thanks a ton for this!

**Pull request merged**
