### PR TITLE
Add floating windows preset sizes

### PR DESCRIPTION
**Pull request by 3ximus**
Hey  man!
I wanted this feature so I decided to add it. It allows me to set a fixed size when making windows float based on a percentage of the screen size, and automaticly put them in the center.
It should not interfere with anything but if you dont want to add it to your project feel free to decline the pull request. Also, a lot of lines seem afected because I remove trailing white spaces automaticly.
Cheers

### CODE REVIEW

**Comment by Jazqa** [comment]
I really appreciate the pull-requests as I have not been able to pay enough attention to the script lately. Definitely testing and merging this as soon as I can. Thanks a ton for contributing!

**Comment by 3ximus** [comment]
I'm also simplifying moving windows between screens because this seems kind of a mess and there is a simple way to do this, I'm just having problems with javascript modular arithmetic

**Comment by Jazqa** [comment]
This is quite brilliant. I'm going to change the feature a bit in near future, but I'm still going to keep this version available through the configuration interface. I've been thinking of restoring the original size and position whenever a window is removed from tiling.

Probably going to have float-behavior options along the lines:

```
Placement:                                   Size:
Center                                       Custom (Width, Height)
Original                                     Original
```

**Comment by 3ximus** [comment]
yeah that sounds cool! 👍

**Pull request merged**
