### PR TITLE
Leaving empty desktop behavior and UI tooltips

### PR DESCRIPTION
**Pull request by 3ximus**
Hey man its me again,
The behavior when you leave a desktop if all the windows on it were closed is useful, but sometimes its annoying if you have floating windows. I decided to make a setting for it that will stop the script from leaving the desktop when you close a window. However, I wanted to make it as a checkbox (and I also made "ignoreJava" and "liveTiling" as a checkbox) However I'm not able to extract the boolean value out of it. It seems to always return true even though the checkbox in unchecked. 

I've found checkbox implemented on this other tiling script ([code](https://github.com/faho/kwin-tiling/blob/364255929f5f7742cef23cfc7203df10495d6848/contents/code/tile.js#L111) and [config xml](https://github.com/faho/kwin-tiling/blob/364255929f5f7742cef23cfc7203df10495d6848/contents/config/main.xml#L12)), and I saw the same thing on some examples that KDE has online [here](https://cgit.kde.org/kdeexamples.git/tree/kconfigxt/example.kcfg#n12).

But they don't seem to work... Do you have any clue about why this is happening and if we could make this work?
I don't know how to debug this, the only way I can get the output from running the script is wih KWin interactive console, but that seems to only run the script and ignore the configurations...

Also I added the tooltips from the config XML file to the UI so that the options are easier to interpret.

### CODE REVIEW

**Comment by Jazqa** [comment]
Brilliant. I actually thought about changing some of the comboboxes to checkboxes yesterday myself. I've also been meaning to drop the somewhat annoying desktop switch for a while now. Thank you once again for contributing!

As an unrelated comment - I've started re-writing the script from scratch despite my lack of free time. The current state of the script is bugging me out and most of the feature suggestions are quite time consuming to implement to the current code. I'm quite sure I can squash the code by two thirds by rewriting and streamlining the script. All of the contributions are still welcome as I have no clue when I'll be able to complete the rewritten version and I'll be copying a ton of code from the main branch anyways.

**Comment by 3ximus** [comment]
As I said in the comment the checkboxes are not actually working, I can't get the Boolean value out of them, I was actually hoping you could help with that before merging 😄 . And since I also replaced `liveTiling` and `ignoreJava` this might break a few custom configurations.

It's cool that you are rewriting the script, possibly make it into multiple files so that its easier to maintain too.

Cheers!

**Comment by Jazqa** [comment]
>It's cool that you are rewriting the script, possibly make it into multiple files so that its easier to maintain too.

Couldn't get the QML/Declarativescript variant to run so I'm splitting the files in a rather... [primitive](https://github.com/Jazqa/kwin-quarter-tiling/tree/rework/contents/code) way :rofl: 

I really wish the API supported a tad more modern JavaScript.

**Comment by 3ximus** [comment]
Ahah yes, that is nasty 😆 
The repo that I mentioned on my first comment also did a script startup in QML, did you look into it?

**Comment by Jazqa** [comment]
Yep. I've found two scripts using QML and I've tried to copy them both off and I've failed miserably. I'm also currently unaware how to debug a QML-based KWin script as the interactive console only accepts JavaScript.

Nevertheless, the current mess should be quite compatible with QML once I get it to start the script.

**Comment by 3ximus** [comment]
I'll give a try on the QML file when I have the chance and I'll let you know if I make an progress.
Your only way to debug the script so far is with the interactive console?

**Comment by Jazqa** [comment]
Thus far, yes. It's awful and there's probably a better way but I'd rather spend my time creating the script than finding better ways to do it. KWin scripting isn't exactly popular so most of the resources regarding it are extremely old. Anyways, I'll create a new issue for the rewrite for further discussion.

**Comment by Jazqa** [comment]
"Solved" the checkbox issue. It's most likely a type error between the JavaScript API and QML. Using `readConfig("live", false).toString() === "true"` works. I'll re-merge this as soon as I can.

**Comment by 3ximus** [comment]
Nice! Do you mind me making another pull request for these changes on the master branch?

**Comment by Jazqa** [comment]
That'd be awesome. I'm not on my desktop until late tonight, but I can test and merge it on my laptop :+1:

**Pull request merged**
